### ISSUE TITLE
Food for Kubernetes control plane

### ISSUE THREAD

**Issue by guicassolato** [3scale/authorino#5]
To improve UX while deploying and maintaining Authorino onto Kubernetes clusters and at the same time ensure a single source of truth for configs, authorization policies, etc, we need to specify some Kubernetes Custom Resource Definitions (CRDs) and controller.

Here's a kick-off proposition for a set of Kubernetes custom resources (CRs) modeling the config exemplified in [examples/config.yml](https://github.com/3scale/authorino/blob/4f0b6e9fdd6e164aae9290f175df4d987edbfb1a/examples/config.yml) (or [examples/openshift](https://github.com/3scale/authorino/blob/4f0b6e9fdd6e164aae9290f175df4d987edbfb1a/examples/openshift)). Hopefully we can work on this until it's mature enough for a proper PR with the CRDs it will induce.

```yaml
apiVersion: api.ostia.3scale.net
kind: AuthProvider
metadata:
  name: keycloak
spec:
  endpoint: http://keycloak-discovery.redhat-sso.svc.cluster.local:8080/auth/realms/ostia
---
apiVersion: api.ostia.3scale.net
kind: OAuthClient
metadata:
  name: authorino
spec:
  providerRef:
    name: keycloak
  credentials:
    client_id: authorino
    client_secret: 2e5246f2-f4ef-4d55-8225-36e725071dee
---
apiVersion: api.ostia.3scale.net
kind: OAuthClient
metadata:
  name: uma-resource-fetcher
spec:
  providerRef:
    name: keycloak
  credentials:
    client_id: pets-api
    client_secret: 523b92b6-625d-4e1e-a313-77e7a8ae4e88
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-policy
data:
  policy.rego: |
    allow {
      http_request.method == "GET"
      path = ["pets"]
    }

    allow {
      http_request.method == "GET"
      own_resource
    }

    allow {
      http_request.method == "GET"
      path = ["stats"]
      is_admin
    }

    own_resource {
      some petid
      path = ["pets", petid]
      resource := object.get(metadata, "uma", [])[0]
      owner := object.get(object.get(resource, "owner", {}), "id", "")
      subject := object.get(identity, "sub", object.get(identity, "username", ""))
      owner == subject
    }

    is_admin {
      identity.realm_access.roles[_] == "admin"
    }
---
apiVersion: api.ostia.3scale.net
kind: OPAPolicy
metadata:
  name: my-inline-rego-policy
spec:
  type: inline
  valueFrom:
    configMapKeyRef:
      name: echo-policy
      key: policy.rego
status:
  policyId: 40f5976b-edf9-42f5-8c85-010d4a9992b3 # auto-generated by the controller (?)
---
apiVersion: api.ostia.3scale.net
kind: JWTClaimSet
metadata:
  name: echo-api-audience
spec:
  match:
    http:
      path: '/api/*'
  claim:
    aud: api
---
apiVersion: api.ostia.3scale.net
kind: ServiceConfig
metadata:
  name: echo-api
spec:
  host:
    - echo-api.svc.cluster.local
    - echo-api.authorino.apps.dev-eng-ocp4-5.dev.3sca.net
  identity:
    - protocol: oidc
      name: oidc-authn
      providerRef: keycloak
  metadata:
    - protocol: userinfo
      identitySource: oidc-authn
      clientRef: authorino
    - protocol: uma
      identitySource: oidc-authn
      clientRef: uma-resource-fetcher
  authorization:
    - type: OPAPolicy
      name: my-inline-rego-policy
    - type: JWTClaimSet
      name: echo-api-audience
      enabled: false
---
apiVersion: api.ostia.3scale.net
kind: Broker
metadata:
  name: authorino
spec:
  serviceConfigs:
    - name: echo-api
      enabled: true
```

**Comment by didierofrivia** [comment]
It's looking good, a couple of questions / suggestions here:

1. We probably would like to start using K8s Secrets for credentials such as the ones for Keycloak.
2. For the OPA policies, do you have an example for file config Rego? or getting it from somewhere else than a `ConfigMap` where it's defined inline? I think the ConfigMap approach is super valid, but maybe when we craft a controller, maybe we would like to get  them from an external service or a config file. 
3. For the kind of authorino, I'd be more explicit, and call it `AuthBroker` instead of just the abstract `Broker`. We might have in the future different "brokers" for integrated services consuming external APIs, like what it could happen with Billing, Dev Portal, etc...
4. For the `JWTClaimSet` kind, maybe the match should be array?
5. Would it make sense to abstract the `AuthProvider` to a simple `ConfigMap` or we are expecting to have a broader spec?

Those are a few that came to my mind, we could discuss them further on our next sync. Great work !!!

**Comment by guicassolato** [comment]
> It's looking good, a couple of questions / suggestions here:
> 
> 1. We probably would like to start using K8s Secrets for credentials such as the ones for Keycloak.
> 2. For the OPA policies, do you have an example for file config Rego? or getting it from somewhere else than a `ConfigMap` where it's defined inline? I think the ConfigMap approach is super valid, but maybe when we craft a controller, maybe we would like to get  them from an external service or a config file.
> 3. For the kind of authorino, I'd be more explicit, and call it `AuthBroker` instead of just the abstract `Broker`. We might have in the future different "brokers" for integrated services consuming external APIs, like what it could happen with Billing, Dev Portal, etc...
> 4. For the `JWTClaimSet` kind, maybe the match should be array?
> 5. Would it make sense to abstract the `AuthProvider` to a simple `ConfigMap` or we are expecting to have a broader spec?
> 
> Those are a few that came to my mind, we could discuss them further on our next sync. Great work !!!

All very good points, @didierofrivia. I'll try to comment on each one...

1. I see no problem with that. Imagine that `client_secret` could be written, e.g.

```yaml
client_secret:
  valueFrom:
    secretRef:
      name: ...
      key: ...
```

2. I think there are multiple possible approaches here. The one I exemplified is for "inline" Rego policies that will be assembled by Authorino into a template that adds a few things, and then registered in the OPA service using OPA's Policy REST API. OPA also admits policy files referred in the command line, which could be a different option, with or without using the ConfigMap (as Kubernetes volumes can be mounted in many different ways/different possible sources). However, I think this may be a more complicated approach because it's important that Authorino points to OPA the policy to be evaluated in each request by ID of the policy, so we can have multiple policies registered in OPA and evaluate only the ones that apply to a given API. Therefore building policy from an external source would preferably be via Authorino as well. So I can imagine something like the following:

```yaml
apiVersion: api.ostia.3scale.net
kind: OPAPolicy
metadata:
  name: my-external-rego-policy
spec:
  type: http | redis
  endpoint: ...
status:
  policyId: 2987eb49-d7a4-42b6-90c7-6fc4dd26035b
```

3. Ok. Good for me.

4. It could be, I guess. That `JWTClaimSet` example actually came yet from our initial talks during the Ostia PoC and, to be fair, I think nobody has put a lot of thought on it so far. I think what we want is a way to represent the properties of the request to be matched in order to trigger the evaluation of each corresponding set of JWT claims. "Properties of the request" can be anything – path, query string, fragment, protocol, domain, verb, header, etc – either way, we need to define what multiple matching properties (conditions) would mean. It can mean ALL the conditions must match to trigger the rule or ANY condition needs to match to trigger the rule. For the former, an array of paths, for example, would not make any sense; instead, one would want in this case to attach multiple different `JWTClaimSet`s to the config.

5. Right now, `AuthProvider` is kind of a mixin. We merge its data into the OIDC identity verification config and into the `OAuthClient` configs whose `identitySource` match. In the future, I can see some use for the CRD
    i. maybe to abstract in the middle the different types of "auth providers", like when it's OIDC versus when it's SAML;
    ii. to model the settings for caching for example.

Thanks for the comments. Please let me know what you think of the replies and feel free to propose alternatives.
